plugin 'cocoapods-fix-react-native'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

target 'xoxo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xoxo
  #pod 'Fabric'
  #pod 'Crashlytics'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#  pod 'React', :path => '../node_modules/react-native', :subspecs => [
#    'Core',
#    'RCTImage',
#    'RCTNetwork',
#    'RCTText',
#    'RCTWebSocket',
#    'DevSupport'
#  ]
  pod 'React', path: '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTActionSheet',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'DevSupport'
    ]
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  target 'xoxoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'xoxo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xoxo-tvOS

  target 'xoxo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
